#!/bin/bash

# This is an initial script to automate the acquisition of software.

# usage: $> sudo ./bashConfigure <--- install, copy, and source dotfiles
# $> sudo ./bashConfigure install <--- install only the packages
# $> sudo ./bashConfigure copy <--- copy dotfiles
# $> sudo ./bashConfigure source <--- source dotfiles
# add-apt-repository universe

# now the packages repo is up to date, begin installing programs:

function install {
  if [[ $(uname) == "Darwin" ]]; then
      echo "DARWIN WINS!"
      echo "install homebrew"
      # Check for Homebrew, install if we don't have it
      if test ! $(which brew); then
        echo "Installing homebrew..."
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      fi

      # Update homebrew recipes
      brew update

      # install some goodies
      brew install vim \
          neovim \
          node \
          emacs \
          curl \
          tmux \
          tree \
          tldr \
          the_silver_searcher \
          ripgrep \
          jq \
          xq \
          docker \
          z

  else
    echo "tis but a nix"
    apt-get update -y
    apt-get upgrade -y
    apt-get install -y htop \
                 tree \
                 node \
                 vim \
                 emacs \
                 curl \
                 tmux \
                 silversearcher-ag \
                 docker.io \
                 gcc \
                 g++ \
                 tig \
                 jq

  fi
  #install z-script for better managing
  wget https://raw.githubusercontent.com/rupa/z/master/z.sh

  # For neovim
  npm install -g tree-sitter-cli
}

# now that git is installed, begin bringing in config files.

mkdir -p ~/.config

copy_dotfiles() {
  # Copy config files over to ~/ directory
  # use symlinks because we can source easier
  if [[ $(uname) == "Darwin" ]]; then
    cp -r $(PWD)/.bashrc ~/
    cp -r $(PWD)/.bash_aliases ~/
    cp -r $(PWD)/.tmux ~/
    cp -r $(PWD)/.emacs.d ~/
    cp -r $(PWD)/.vim ~/
    cp -r $(PWD)/.vimrc ~/
    cp -r $(PWD)/.tmux.conf ~/
    cp -r $(PWD)/.git-prompt.sh ~/
  else
    cp -r .bash* ~/
    cp -r .tmux ~/
    cp -r .emacs.d ~/
    cp -r .vim ~/
    cp -r .vimrc ~/
    cp -r .tmux.conf ~/
    cp -r .git-prompt.sh ~/
  fi
  ## Vim
  if [ -d ~/.vim/autoload ] && [ -d ~/.vim/bundle ]; then
    # Get Pathogen:
    mkdir -p ~/.vim/autoload ~/.vim/bundle && \
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
  fi

  mkdir -p ~/.config
  cp -r $(PWD)/nvim ~/.config
}

if [[ $1 == "install" || -z $1 ]]; then
  install

fi

if [[ $1 == "copy" || -z $1 ]]; then
  copy_dotfiles
fi

if [[ $1 == "source" || -z $1 ]]; then
  source ~/.bashrc
fi

if [[ $1 == "cs" ]]; then
  copy_dotfiles
  source ~/.bashrc
fi
