#!/bin/bash

# This is an initial script to automate the acquisition of software.
# It assumes the apt-get package manager is installed, and the script is run under sudo

add-apt-repository universe

apt-get update
apt-get upgrade

# now the packages repo is up to date, begin installing programs:

apt-get install -y htop \
				   tree \
				   vim \
				   emacs \
				   curl \
				   tmux \
				   silversearcher-ag \
				   docker \
				   gnome-session-flashback \
				   metacity \
				   eclipse \
				   gcc \
				   g++

# now that git is installed, begin bringing in config files.

# Copy all the configuration files to the home directory
cp ~/git/nixConfig/nixSettings/.bashrc ~/
cp ~/git/nixConfig/nixSettings/.bash_aliases ~/
cp ~/git/nixConfig/nixSettings/.vimrc ~/
cp ~/git/nixConfig/nixSettings/.tmux.conf  ~/
cp ~/git/nixConfig/nixSettings/.git-prompt.sh ~/
cp -R ~/git/nixConfig/nixSettings/.emacs.d ~/
cp -R ~/git/nixConfig/nixSettings/.vim/ ~/

# Unpack and copy config files over to ~/ directory

## Vim
# Get Pathogen:
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Configure the keyboard: 
# 1. swap the caps lock with control keys - Source: www.noah.org/wike/CapsLock_Remap: this is accomplished in the bashrc file
# 2. turn the right shift key into a forward delete key
